// <auto-generated />
using System;
using Atelier.Cats.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atelier.Cats.DataAccess.Entities.Migrations
{
    [DbContext(typeof(AtelierCatsContext))]
    [Migration("20211020164318_init-create")]
    partial class initcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atelier.Cats.DataAccess.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtelierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("AtelierId");

                    b.ToTable("Cat");
                });

            modelBuilder.Entity("Atelier.Cats.DataAccess.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengerOneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengerTwoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VoteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChallengerOneId", "ChallengerTwoId");

                    b.HasAlternateKey("ChallengerTwoId", "ChallengerOneId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Challenge");
                });

            modelBuilder.Entity("Atelier.Cats.DataAccess.Entities.Challenge", b =>
                {
                    b.HasOne("Atelier.Cats.DataAccess.Entities.Cat", "ChallengerOne")
                        .WithMany()
                        .HasForeignKey("ChallengerOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Cats.DataAccess.Entities.Cat", "ChallengerTwo")
                        .WithMany()
                        .HasForeignKey("ChallengerTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Cats.DataAccess.Entities.Cat", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengerOne");

                    b.Navigation("ChallengerTwo");

                    b.Navigation("Winner");
                });
#pragma warning restore 612, 618
        }
    }
}
